import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import RecoilRootWrapper from "@/store/RecoilWrapper";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} relative px-4 pb-24 pt-20`}>
        <Header />
        <RecoilRootWrapper>{children}</RecoilRootWrapper>
        <Footer />
      </body>
    </html>
  );
}
