// app/layout.tsx
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import RecoilRootWrapper from "@/store/RecoilWrapper";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap", // 추가: 로딩 시 FOUT(Flash of Unstyled Text) 방지
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="relative px-4  pt-20 flex flex-col min-h-screen max-w-xl mx-auto">
          <Header />
          <RecoilRootWrapper>{children}</RecoilRootWrapper>
          <Footer />
        </div>
      </body>
    </html>
  );
}
